### ISSUE TITLE
Dummy API key?

### ISSUE THREAD

**Issue by enryH** [ploomber/jupyblog#10]
I just stumbled upon your repo and had a look how it works. Hope this is just a placeholder:

https://github.com/ploomber/jupyblog/blob/0fd97813548ba08fd486c43d836286c54b63e903/src/jupyblog/cli.py#L16

**Comment by edublancas** [comment]
hi, thanks for your feedback!

we have telemetry to measure usage. that's why we have that key there. It doesn't give access to any sensitive information, nor grants any sensitive permissions.
